# ==========================================
# FILE: calibrate_now.py
# ==========================================
import time
import board
import busio
from adafruit_ads1x15.ads1015 import ADS1015
from adafruit_ads1x15.analog_in import AnalogIn

# === 1. TARGET CONSTANTS (The "Baseline" you want) ===
TARGET_MQ4 = 0.128
TARGET_MQ135 = 0.156
TARGET_TGS2602 = 0.032

def perform_calibration():
    print("--- STARTING AUTO-CALIBRATION ---")
    
    # Initialize Sensors
    i2c = busio.I2C(board.SCL, board.SDA)
    ads = ADS1015(i2c)
    
    # Read Raw Voltages (Take average of 10 readings for accuracy)
    raw_mq4 = 0
    raw_mq135 = 0
    raw_tgs = 0
    
    print("Reading sensors...")
    for _ in range(10):
        raw_mq4 += AnalogIn(ads, 0).voltage
        raw_mq135 += AnalogIn(ads, 1).voltage
        raw_tgs += AnalogIn(ads, 2).voltage
        time.sleep(0.1)
        
    # Calculate Average Raw Voltage
    avg_mq4 = raw_mq4 / 10
    avg_mq135 = raw_mq135 / 10
    avg_tgs = raw_tgs / 10
    
    # === 2. CALCULATE NEW OFFSETS ===
    # Formula: Offset = Current_Raw - Desired_Target
    new_offset_mq4 = avg_mq4 - TARGET_MQ4
    new_offset_mq135 = avg_mq135 - TARGET_MQ135
    new_offset_tgs = avg_tgs - TARGET_TGS2602
    
    print(f"New MQ4 Offset: {new_offset_mq4:.3f}")
    print(f"New MQ135 Offset: {new_offset_mq135:.3f}")
    print(f"New TGS Offset: {new_offset_tgs:.3f}")

    # === 3. OVERWRITE THE CONFIG FILE ===
    config_content = f"""# =========================================================
# SENSOR CALIBRATION CONFIGURATION
# =========================================================
# AUTO-GENERATED BY calibrate_now.py
# Date: {time.ctime()}
# =========================================================

OFFSETS = {{
    "MQ4": {new_offset_mq4:.4f},      # Target: {TARGET_MQ4}
    "MQ135": {new_offset_mq135:.4f},    # Target: {TARGET_MQ135}
    "TGS2602": {new_offset_tgs:.4f},   # Target: {TARGET_TGS2602}
    "NIR": 0
}}
"""
    
    try:
        with open("sensor_config.py", "w") as f:
            f.write(config_content)
        print("✅ sensor_config.py updated successfully!")
        return True
    except Exception as e:
        print(f"❌ Error writing config: {e}")
        return False

if __name__ == "__main__":
    perform_calibration()